namespace NineYi.Ai.CodeReview.Application.Options;

/// <summary>
/// 控制哪些檔案不需要送進 AI Code Review 的排除規則。
/// 在 IRepoHostClient 回傳 diff 清單前統一套用，三個平台共用同一份設定。
/// </summary>
public class FileExcludeOptions
{
    public const string SectionName = "FileExclude";

    /// <summary>
    /// 路徑前綴黑名單。
    /// 檔案路徑只要包含清單中任一字串（不區分大小寫），該檔案即被排除。
    /// 例如："/AutoGenerated/"、"/i18n/"、"/migrations/"。
    /// </summary>
    public List<string> ExcludedPathPrefixes { get; set; } = [];

    /// <summary>
    /// 副檔名黑名單（含句點）。
    /// 副檔名符合清單中任一項（不區分大小寫），該檔案即被排除。
    /// 例如：".designer.cs"、".typegen.ts"、".g.cs"。
    /// </summary>
    public List<string> ExcludedFileExtensions { get; set; } = [];
}
